/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package gradle.poc;

public class Library {
    public boolean someLibraryMethod() {
        return true;

    }

    public boolean newMothodForDemo() {
        return false;
    }
}
